versão : 2
atualizações :
- pacote-ecossistema : npm
  diretório : " / "
  horário :
    intervalo : diário
  limite de solicitações de abertura : 10
  ignorar :
  - nome da dependência : " @ types / node "
    versões :
    - 14,14,22
    - 14,14,24
    - 14,14,25
    - 14,14,26
    - 14,14,28
    - 14,14,30
    - 14,14,31
    - 14.14.32
    - 14,14,33
    - 14,14,34
    - 14,14,35
    - 14,14,36
    - 14,14,37
    - 14,14,39
    - 14,14,41
    - 15.0.0
  - nome da dependência : eslint-config-mais bonita
    versões :
    - 8.0.0
    - 8.1.0
    - 8.2.0
    - 8.3.0
  - nome da dependência : next-pwa
    versões :
    - 5.0.4
    - 5.0.5
    - 5.0.6
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.15
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - nome da dependência : eslint
    versões :
    - 7.21.0
    - 7.22.0
    - 7.25.0
  - dependency-name : " @ storybook / addon-essentials "
    versões :
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
    - 6.2.9
  - nome da dependência : " @ storybook / react "
    versões :
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
    - 6.2.9
  - dependency-name : " @ testing-library / jest-dom "
    versões :
    - 5.11.10
    - 5.12.0
  - nome da dependência : " @ babel / core "
    versões :
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.16
    - 7.13.8
  - nome da dependência : componentes com estilo jest
    versões :
    - 7.0.4
  - nome da dependência : eslint-plugin-mais bonito
    versões :
    - 3.3.1
    - 3.4.0
  - nome da dependência : y18n
    versões :
    - 4.0.1
    - 4.0.2
  - nome da dependência : " @ typescript-eslint / parser "
    versões :
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
  - nome da dependência : componentes estilizados
    versões :
    - 5.2.2
  - nome da dependência : próximo
    versões :
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.1.2
  - nome da dependência : husky
    versões :
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.2.0
    - 6.0.0
  - nome da dependência : " @ types / jest "
    versões :
    - 26.0.20
    - 26.0.22
  - nome da dependência : eslint-plugin-react
    versões :
    - 7.23.0
    - 7.23.1
  - nome da dependência : react-dom
    versões :
    - 17.0.2
  - nome da dependência : reagir
    versões :
    - 17.0.2
  - nome da dependência : " @ typescript-eslint / eslint-plugin "
    versões :
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
  - nome da dependência : " @ types / styled-components "
    versões :
    - 5.1.8
    - 5.1.9
  - nome da dependência : " @ types / react "
    versões :
    - 17.0.3
  - dependency-name : typescript
    versões :
    - 4.2.2
    - 4.2.3
  - nome da dependência : " @ babel / preset-typescript "
    versões :
    - 7.12.17
    - 7.13.0
  - dependency-name : " @ testing-library / react "
    versões :
    - 11.2.3
    - 11.2.5